### ISSUE TITLE
It doesn't work after changing my model

### ISSUE THREAD

**Issue by evergreenqingyu** [DominikDoom/a1111-sd-webui-tagcomplete#149] opened 2023-03-28 02:33 UTC
I'm sorry to disturb you, but I don't know if this is my own problem.The extension doesn't work after changing my model,only reload the webui can resuse it.
![1](https://user-images.githubusercontent.com/82428916/228112227-097dfc6b-e045-47d1-a539-60b0ed7eee1a.png)
![2](https://user-images.githubusercontent.com/82428916/228112250-f3044200-c808-4a7e-b62f-32a34f17e766.png)

**Comment by DominikDoom** [comment] 2023-03-28 05:52
I can't reproduce it on my system, what settings are you using for your tag autocomplete? It might be related to a blacklist/whitelist bug, although that works as intended for me.
Also, since the recent Gradio update broke a lot of things, please try without any other extensions enabled to see if the issue also exists standalone.

**Comment by sashasubbbb** [comment] 2023-03-28 06:16
Yeah, i've got the same problem with older version of webui (waiting for new gradio to be stable). 
My commit is https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

**Comment by evergreenqingyu** [comment] 2023-03-28 06:18
Thanks for your answer.After trying, regardless of whether I input the model into the tag whitelist or not, the problem still exists, and then I removed all extensions except tagcomplete, with the same result.
My webui version is the same a9fed7c,uploaded on Mar 14, 2023.
![1](https://user-images.githubusercontent.com/82428916/228142712-3fdc1a03-4097-44ac-9c11-39097ab21091.png)
![2](https://user-images.githubusercontent.com/82428916/228142728-f2c596a5-53b9-40e2-a9ad-16bda976d3c4.png)
![3](https://user-images.githubusercontent.com/82428916/228142737-7579277a-02aa-4dfd-9a23-2b1bf46bff29.png)

**Comment by DominikDoom** [comment] 2023-03-28 07:27
Yeah, then this is likely an issue due to the changes for the new Gradio. A few UI selectors changed, so the current version probably fails to get the name of the currently selected model after it changes, which then crashes the script. I'll try to add a fallback later today, in the meantime you can try rolling tag autocomplete back to https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/e7fa5aca18d20091a232df2dbd5f9df12b3b145b, before the changes were merged in.

**Closed** 2023-03-28 18:49 UTC

**Comment by DominikDoom** [comment] 2023-03-28 18:52
It was indeed the model change method for new gradio causing an error in the old version like I suspected.
I added a fallback for the old version, so it should now be possible to use the current tag autocomplete version again without also updating the webui.
