### ISSUE TITLE
its broken

### ISSUE THREAD

**Issue by IkariDevGIT** [DominikDoom/a1111-sd-webui-tagcomplete#125] opened 2023-02-05 18:46 UTC
Uncaught (in promise) ReferenceError: getTextAreas is not defined
    setup http://127.0.0.1:7861/file=D:/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1675622356.8616462:1201

problem:

    // Find all textareas
    let textAreas = getTextAreas();

**Comment by DominikDoom** [comment] 2023-02-05 18:53
Definitely working for me, I also did not change anything regarding that function since December 18th when I first added it.
In the autocomplete extension's javascript folder, do you have the _textAreas.js file? That holds the relevant function.

**Comment by IkariDevGIT** [comment] 2023-02-05 18:55
@DominikDoom yes

**Comment by IkariDevGIT** [comment] 2023-02-05 18:56
@DominikDoom ok, got it to work by removing the _textAreas.js file and moving everything over into the main js file. i use firefox, so maybe that's a problem

**Comment by DominikDoom** [comment] 2023-02-05 18:59
Shouldn't be. As I said, this setup hasn't changed since December 18th and is confirmed working for me in Chrome, Firefox, and Edge. Did it work for you before?

**Comment by IkariDevGIT** [comment] 2023-02-05 19:01
yes, idk maybe its some extension

**Comment by DominikDoom** [comment] 2023-02-05 19:05
The javascript depends on the _textAreas file being evaluated by the browser before the main file, but that should be the case since the webui just appends the script in alphabetical order, so since the aforementioned starts with _, it should always come first.

Since it's javascript it should also not really be influenced by other extensions.
Still, if you can, it would be nice to try out the original setup with only autocomplete enabled to see if it's a conflict.

**Comment by IkariDevGIT** [comment] 2023-02-08 16:52
idk, still getting this error:

Uncaught (in promise) ReferenceError: getTextAreas is not defined
    setup http://127.0.0.1:7860/file=D:/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/javascript/tagAutocomplete.js?1675874503.265476:1201

**Comment by IkariDevGIT** [comment] 2023-02-08 16:54
ok, seems that it works now. deleted my cookies, now it works

**Comment by DominikDoom** [comment] 2023-02-08 16:56
It doesn't use cookies, but maybe a cache issue? Did you try force refreshing with CTRL+F5 before?

**Comment by IkariDevGIT** [comment] 2023-02-08 17:26
multiple times, like 5 times every time i started sd

**Comment by DominikDoom** [comment] 2023-02-08 17:39
Strange. Well, if it works now, I'm closing this. If it happens again I'll need more details though as I still haven't been able to reproduce it.

**Closed by DominikDoom** 2023-02-08 17:39 UTC
