### ISSUE TITLE
Google Auto Translate for chrome corrupts tag hints.

### ISSUE THREAD

**Issue by surfishs** [DominikDoom/a1111-sd-webui-tagcomplete#144] opened 2023-03-26 04:33 UTC
The only way to fix it is to restart the page, or to disable translation of this page.

**Comment by DominikDoom** [comment] 2023-03-26 08:47
I couldn't reproduce the problem on my chrome (tags weren't getting translated no matter what language I chose), but after searching found a way that supposedly tells Translate to ignore parts of the page. Let me know if that solved the problem for you.

**Comment by surfishs** [comment] 2023-03-27 02:21
I am trying to find out why this issue is triggered, please give me some time, it is still triggered in some cases

**Comment by surfishs** [comment] 2023-03-27 14:05
@DominikDoom

**Comment by surfishs** [comment] 2023-03-28 04:39
I used the following plugin and can confirm that tag completion failed when I used Google Translate, which comes with the browser.
https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN
https://github.com/journey-ad/sd-webui-bilingual-localization
Before translation：
![QQ截图20230328123725](https://user-images.githubusercontent.com/96485650/228129736-c6b26d07-6214-489f-b352-f2ca21ee77e0.png)
translation：
![QQ截图20230328123735](https://user-images.githubusercontent.com/96485650/228129754-5eca60fb-85cd-41bc-affa-142451c274e9.png)
![QQ截图20230328123744](https://user-images.githubusercontent.com/96485650/228129758-86c9f61c-d575-4852-8969-86f7adaa4925.png)

**Comment by DominikDoom** [comment] 2023-03-28 18:54
Can you check it again with the current tag autocomplete version? I pushed a fix for another problem related to older webui versions, but have a feeling it might be related to this too. The symptoms were similar at least.

**Comment by surfishs** [comment] 2023-03-29 02:52
i will try

**Comment by DominikDoom** [comment] 2023-08-27 15:20
Closing this as stale, feel free to reopen if it is still relevant.

**Closed by DominikDoom** 2023-08-27 15:20 UTC
