### ISSUE TITLE
extension not working.

### ISSUE THREAD

**Issue by quallybeach** [DominikDoom/a1111-sd-webui-tagcomplete#102] opened 2023-01-03 07:06 UTC
Autocompleted tags not showing up.
![image_2023-01-03_020339721](https://user-images.githubusercontent.com/121709828/210312598-acb76860-402b-4eed-a652-290b8b2d76de.png)
![image_2023-01-03_020359323](https://user-images.githubusercontent.com/121709828/210312619-18082621-ca2d-47ba-a383-8e39b5d4fec5.png)
![image_2023-01-03_020438002](https://user-images.githubusercontent.com/121709828/210312677-f95c1dd4-c701-4ea8-b65b-0d22cd6c2a77.png)
Im new to this and dont really know coding terms, so could you please explain what i'm doing wrong?

**Comment by maniakid** [comment] 2023-01-03 07:56
Yes, same here, deleted and reinstalled, type prompt but no dropdown menu showing, no error outputs.

**Comment by DominikDoom** [comment] 2023-01-03 10:18
This was caused by a change in the webui, fixed in 2ba513bedcea42b57f8135b797e21e1d9882650f and #101.
Please try it out and see if that fixed it for you. Sorry for the inconvenience.

**Closed** 2023-01-03 10:27 UTC

**Comment by quallybeach** [comment] 2023-01-04 08:43
> This was caused by a change in the webui, fixed in [2ba513b](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/2ba513bedcea42b57f8135b797e21e1d9882650f) and #101. Please try it out and see if that fixed it for you. Sorry for the inconvenience.

Hey sorry I don't mean to sound dumb but I'm really new to this. like i just started using SD a few days ago. could you please explain to me how I go about doing that?

**Comment by DominikDoom** [comment] 2023-01-04 08:59
Just update both the webui and the extension, the current versions of both should work.
If you installed them using git you can just open a command prompt and type `git pull` in the webui root and extension folder.

The extension can alternatively also be updated using the Extensions tab in the webui, it will have a Check for updates button. If an extension shows "behind" afterward, just click on Apply and restart.

**Comment by quallybeach** [comment] 2023-01-04 10:25
> Just update both the webui and the extension, the current versions of both should work. If you installed them using git you can just open a command prompt and type `git pull` in the webui root and extension folder.
> 
> The extension can alternatively also be updated using the Extensions tab in the webui, it will have a Check for updates button. If an extension shows "behind" afterward, just click on Apply and restart.

![image_2023-01-04_052055461](https://user-images.githubusercontent.com/121709828/210534158-bbce613c-0615-4203-9ecb-b47ec15db277.png)
![image_2023-01-04_052119405](https://user-images.githubusercontent.com/121709828/210534234-a48cb241-dcab-417f-9379-a31769abc36d.png)
![image_2023-01-04_052421382](https://user-images.githubusercontent.com/121709828/210534763-0e42b36c-518b-4fa4-ad39-534626ddc119.png)
![image_2023-01-04_052519416](https://user-images.githubusercontent.com/121709828/210534944-ba4348d0-24b8-4291-8485-aa0b4318a4a4.png)

:(

**Comment by DominikDoom** [comment] 2023-01-04 10:34
Any errors in the webui terminal or browser console?

**Comment by maniakid** [comment] 2023-01-04 14:03
Thanks. It works for me now.

But I find another small issue: 

First in the settings page, "Tag filename" is set to "None".

Back to txt2img page, anytime type "__", the wildcards works well, but "<" for embeddings only works if I type "__" first, then backspace delete it, then type "<" again, the dropdown menu shows.

If "Tag filename" is not set to "None", everything works just fine.

**Comment by quallybeach** [comment] 2023-01-05 04:32
> Any errors in the webui terminal or browser console?

nope, everything's working perfect. the extension is there, it has its own page in the settings tab. it just doesn't work.
![image_2023-01-04_233123954](https://user-images.githubusercontent.com/121709828/210702114-0e1342ba-5083-48c1-8304-7fd3c0fec0ff.png)
![image_2023-01-04_233221837](https://user-images.githubusercontent.com/121709828/210702242-993f8cc9-3615-4eda-a0be-a85865df4447.png)

**Comment by DominikDoom** [comment] 2023-01-05 12:34
> nope, everything's working perfect. the extension is there, it has its own page in the settings tab. it just doesn't work.

The script is like 80% javascript (client side), so most important for error detection is the browser console.
Pressing `Ctrl+Shift+I` should work as a hotkey to open the dev tools on most browsers. In the menu that opens, there should be a "Console" tab somewhere. Please go there to see if any javascript errors pop up after the webui has started or while you type.
Another thing you can try is simply typing `allTags` in the console and pressing enter, which should show something like this:
![image](https://user-images.githubusercontent.com/34448969/210780443-6fd5a43b-b287-413e-af5e-9ec5f83ea59d.png)
Just as a check to make sure the client script loaded correctly.

If there isn't anything obvious, I'll need more information.
E.g. Which browser & browser version are you using, on which OS, etc. since it could be an incompatibility issue I wasn't aware of (haven't tried running it on Safari or Opera for example).

**Comment by quallybeach** [comment] 2023-01-06 00:59
![image_2023-01-05_195553255](https://user-images.githubusercontent.com/121709828/210908017-2ba3b49a-e0e3-4b8c-aa4a-45863aec8aa4.png)
![image_2023-01-05_195634149](https://user-images.githubusercontent.com/121709828/210908092-efef23e3-73a6-4875-9ca9-2f2a4a7d72d4.png)
![image_2023-01-05_195858308](https://user-images.githubusercontent.com/121709828/210908356-0268a96e-45ea-4020-9b68-e60caa38bacc.png)

I'm not seeing anything abnormal.

**Comment by DominikDoom** [comment] 2023-01-06 06:27
The red line at the end is an error, it could be related since the script does need to add some listeners to react to typing or settings changes. It could be that for whatever reason it can't find the UI elements on your installation.

Can you expand that line and click on the line number(s) for it? I need to know where it is triggered.
Also, I was wondering this before, the refresh icon and sliders in your webui screenshots look a bit strange. Are you on an older OS or something similar?

**Comment by quallybeach** [comment] 2023-01-06 10:09
> The red line at the end is an error, it could be related since the script does need to add some listeners to react to typing or settings changes. It could be that for whatever reason it can't find the UI elements on your installation.
> 
> Can you expand that line and click on the line number(s) for it? I need to know where it is triggered. Also, I was wondering this before, the refresh icon and sliders in your webui screenshots look a bit strange. Are you on an older OS or something similar?

![image_2023-01-06_050805167](https://user-images.githubusercontent.com/121709828/210978900-63372530-b218-41fe-9ad2-616b348bddd1.png)
![image_2023-01-06_050831963](https://user-images.githubusercontent.com/121709828/210978974-adfdda25-3c37-40cb-949e-2e378ee0b219.png)
![image_2023-01-06_050851452](https://user-images.githubusercontent.com/121709828/210979025-6c8f522e-9c65-4515-9af6-11d79f3d03d9.png)

idk what any of this means, cuz like i said im new to all this coding stuff.

**Comment by DominikDoom** [comment] 2023-01-06 10:17
Yeah, that  squiggly underlined part means the settings button was not found, and due to this error the rest of the script can't continue.

But your code doesn't seem up to date, are you sure you updated both? The current version should look more like this:
```js
let applySettingsButton = gradioApp().querySelector("#tab_settings #settings_submit") || gradioApp().querySelector("#tab_settings > div > .gr-button-primary");
```

**Comment by DominikDoom** [comment] 2023-01-06 10:33
Also, another thing you can try:
Open the webui settings page, right click the "Apply settings" button and click on "Inspect" in the context menu.
The HTML code of that part should look like this:
![image](https://user-images.githubusercontent.com/34448969/210988432-bd12ac10-b5ca-4f66-b504-9592b660308f.png)

You can also try entering `gradioApp().querySelector("#tab_settings #settings_submit")` in the browser console and seeing if it returns an element, instead of null or undefined.

**Comment by quallybeach** [comment] 2023-01-07 04:26
> Yeah, that squiggly underlined part means the settings button was not found, and due to this error the rest of the script can't continue.
> 
> But your code doesn't seem up to date, are you sure you updated both? The current version should look more like this:
> 
> ```js
> let applySettingsButton = gradioApp().querySelector("#tab_settings #settings_submit") || gradioApp().querySelector("#tab_settings > div > .gr-button-primary");
> ```

i mean it says its up to date, i do the "git pull" thing and it always says its up to date, idk how else i would update it.
![image_2023-01-06_232555728](https://user-images.githubusercontent.com/121709828/211130899-a49c5529-82a7-4f58-aa23-5cb362abdfea.png)
![image_2023-01-06_232634357](https://user-images.githubusercontent.com/121709828/211130913-f757226f-1651-4e3e-b3e7-deff12866c93.png)

**Comment by quallybeach** [comment] 2023-01-07 04:35
> 

ur right. this does seem to be the issue, however i have 0 clues on how to fix it.
![image_2023-01-06_233153224](https://user-images.githubusercontent.com/121709828/211131058-48936abb-c531-42dc-97c1-2a6ef5ce89b0.png)

also I searched the line of code that you provided into the browser console and it came up with no results.
![image_2023-01-06_233421805](https://user-images.githubusercontent.com/121709828/211131126-a8d23c0c-48f4-4403-ac51-36918a47a5f3.png)

however being inexperienced in this field, i tried searching it through
![image_2023-01-06_233542885](https://user-images.githubusercontent.com/121709828/211131160-6bb3874f-6e20-4905-9f72-d5b38ee72e1b.png)
![image_2023-01-06_233557771](https://user-images.githubusercontent.com/121709828/211131166-dc48190f-d869-404e-ab3e-2000858fba9b.png)
 the actual console part and it came up with this

**Comment by DominikDoom** [comment] 2023-01-07 09:02
At this point I have no idea, since it found the button when you entered it in the console, it should by all means work in the webui too. That it doesn't reflect the current updates in the code is strange though.

Deleting and reinstalling the extension might be worth a try, maybe something got corrupted. Make sure you don't have a second copy installed somewhere that could interfere. Also, try refreshing the webui site with Ctrl+F5 to clear the site cache, just to make sure it doesn't hold on to the wrong version.

**Comment by quallybeach** [comment] 2023-01-15 05:00
![image_2023-01-15_000033730](https://user-images.githubusercontent.com/121709828/212523702-95a34fda-b656-4b7a-a609-c0f1b24e3147.png)
its a miracle

**Comment by DominikDoom** [comment] 2023-01-15 12:29
@quallybeach Glad to see that you got it working!
So what fixed it in the end? Just reinstalling, or something else?

**Comment by quallybeach** [comment] 2023-01-16 05:03
> @quallybeach Glad to see that you got it working! So what fixed it in the end? Just reinstalling, or something else?

I tried reinstalling it a bunch like a few weeks ago and it did nothing, but i gave it one last try last night and for some reason it worked!

**Comment by aComxhd** [comment] 2023-01-29 13:04
> @quallybeach Glad to see that you got it working! So what fixed it in the end? Just reinstalling, or something else?

it happened on me alike him and solved it in 5 hours,i hope this could help some。
it dosen't work before a week so i back to a stable version (and it worked untill today when i start it),so i think it have a new version and update every thing,and it still don't work,I tyied check update,remove it and reload it (the files in extension floder),crtl f5,before i power off my computer there is no problem in terminal and i check it work and restart the sd
repeatedly, and now i start my computer adn sd and come git see more ,after a generate process ,i find it working when 
i try ti change the tag.
so may after reload the web and the extension still  ((need to restart the computer))?
i can't understand it,(it happend in 5 hour so less disturb so i write a reply)
i hope this have some helpful and i am sorry about my english.
