### ISSUE TITLE
Extension don‘’t work 

### ISSUE THREAD

**Issue by liuzhiyi0531** [DominikDoom/a1111-sd-webui-tagcomplete#103] opened 2023-01-03 07:07 UTC
已经git pull到最新版本
![image](https://user-images.githubusercontent.com/60915579/210312650-48edab17-8016-4702-9acd-015446d0b162.png)

venv "C:\Users\Administrator\Desktop\webui\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 2bc86712ec16cada01a2353f1d978c1aabc84dbb
Installing requirements for Web UI
Launching Web UI with arguments: --deepdanbooru --xformers --precision full --no-half
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [1a7df6b8] from C:\Users\Administrator\Desktop\webui\stable-diffusion-webui\models\Stable-diffusion\Anything-V3.0-pruned-fp32.ckpt
Applying xformers cross attention optimization.
Model loaded.
Textual inversion embeddings loaded(0):
Warning: Bad ui setting value: img2img/Mask mode/value: Draw mask; Default value "Inpaint masked" will be used instead.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by DominikDoom** [comment] 2023-01-03 10:17
This was caused by a change in the webui, fixed in 2ba513bedcea42b57f8135b797e21e1d9882650f and #101.
Please try it out and see if that fixed it for you.

**Comment by MegaScience** [comment] 2023-01-03 10:21
Seems to be working now for me.

**Comment by DominikDoom** [comment] 2023-01-03 10:27
Alright, thanks for the confirmation. I'll close this for now, @liuzhiyi0531 feel free to reopen if you still have the issue.

**Closed by DominikDoom** 2023-01-03 10:27 UTC
