### ISSUE TITLE
Support for vlad's fork.

### ISSUE THREAD

**Issue by Symbiomatrix** [DominikDoom/a1111-sd-webui-tagcomplete#180] opened 2023-05-21 18:06 UTC
Hello dominik, the extension seems to be in rather poor shape when used on vlad's fork for me: no highlighting, missing embeddings (though list is generated), doesn't work after ui restart (I think it might even only work once after installation?).
Have you tested it? Any plans to support it?

Edit: Correction, not working at all was my bad - tried to map a key to None, js didn't like it. Embeddings are functional now. So just the highlighting, I guess.

If it's of any help, getting an uncaught domexception / typeerror for the line `gradioApp().appendChild(acStyle);`.
```
Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at setup (...
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Blocks.svelte:217:11
    at Array.forEach (<anonymous>)
    at Pe (Blocks.svelte:215:9)
    at Blocks.svelte:287:7
```

The list also appears standalone below the prompt area instead of as a popup list, so I guess that's another indication of lacking style.

**Comment by blooest** [comment] 2023-05-23 04:06
I've been using it on Vlad's fork for weeks without any issues. The dropdown pops up as expected and tags listed therein are highlighted as expected. Even the recent bump to Gradio 3.32 has been fine. Are you perhaps running on an outdated build?

**Comment by DominikDoom** [comment] 2023-05-23 07:58
This is a commonly occurring issue due to openpose-editor being outdated and breaking a stock function of the webui this script depends on. I guess I should put it in the known issues section due to how often it comes up. Update that extension and it should be fixed.

Also see #146, #153, #166, #175. Feel free to reopen it if it's not caused by that in your case, but for now I'm closing this as duplicate.

**Closed by DominikDoom** 2023-05-23 07:58 UTC
