### ISSUE TITLE
Ignore key events (specifically arrow keys) if a modifier key is down

### ISSUE THREAD

**Issue by skfoo** [DominikDoom/a1111-sd-webui-tagcomplete#222] opened 2023-08-19 06:48 UTC
The web ui supports using alt+up/down to change the weights of the selected text/lora, however this also activates the tag autocomplete popup at the same time.

Is there any reason for the code to respond to arrow keys while alt/shift/control are pressed? It looks like you can just exit early in tagAutocomplete.js' navigateInList function if event.getModifierState indicates that any modifiers are down.

**Comment by DominikDoom** [comment] 2023-08-19 09:38
I'm not sure what your issue is, I already do exactly that. See the following line:
https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/blob/main/javascript/tagAutocomplete.js#L1116-L1117
It uses the direct event vars instead of getModifierState, but for this case it should be functionally identical.

It will not force-close the popup if it is already open, but at least for weight editing this happens automatically for me due to the text change. And it definitely stops the list from capturing the key press. Works as intended for me:

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/4e408722-641e-4e8e-9ab9-ecb7df1c6184

Also as a side note, at least in the default webui weight editing is only possible with CTRL, and ALT for switching the position of the selected word in the prompt. You can't change it to ALT for weight editing there. Are you using a fork?

**Comment by skfoo** [comment] 2023-08-19 09:51
> Are you using a fork

No I'm using a Mac. I meant Control. This is what happens; Auto1 version 1.5.2 with the latest Chrome.

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/44075232/a514d129-fe01-485b-a6c9-5b9610db3639

Don't know why the popup isn't showing up near the text cursor, it was doing that properly before.

**Comment by DominikDoom** [comment] 2023-08-19 10:00
Ah, I think I see the issue now. The mac command key is event.metaKey, not event.ctrlKey, which I didn't catch before.
I believe it should be fixed now. I don't have a mac to try it out myself, so feel free to reopen if it still has issues.

**Closed by DominikDoom** 2023-08-19 10:00 UTC
